# build image
FROM nginx

WORKDIR /usr/share/nginx/html

COPY . .

#create image
# docker build . -t home

#create container
# docker run -d -p 7777:80 --name demo-container home

#http://localhost:7777
#http://localhost:7777/demo/main.html